#CS4082 - Machine Learning Pipeline
##Lecture 5 - KNN
###Pipeline:
> 1. read
2. split
3. divide
4. train
5. predict
6. evaluate

In [1]:
import numpy as np
import pandas as pd

data ={
    "area":[100,150,200,250,300],
    "bedrooms":[2,3,3,4,5],
    "age":[20,15,10,5,2],
    "price":[200,300,400,500,650]
}

df=pd.DataFrame(data)
df.to_csv("housing.csv",index=False)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

#Step 1. Read (& Preprocess)

In [2]:
df=pd.read_csv("housing.csv")
df.head()

   area  bedrooms  age  price
0   100         2   20    200
1   150         3   15    300
2   200         3   10    400
3   250         4    5    500
4   300         5    2    650

#Step 2. Separate Features & Label

In [3]:
X=df[["area","bedrooms","age"]]
y=df["price"]

#Step 3. Split (divide) the Data

In [4]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

#Step 4. Train Model

In [5]:
#4.1 Create Model

model= LinearRegression()

#4.2 Fit Model

model.fit(x_train,y_train)

LinearRegression()

#Step 5. Predict

In [6]:
y_pred= model.predict(x_test)

#Step 6. Evaluate

In [7]:
rmse= np.sqrt(mean_squared_error(y_test,y_pred))
print("RMSE: ", rmse)

mse= mean_squared_error(y_test,y_pred)
print("MSE: ", rmse)

r2= r2_score(y_test,y_pred)
print("R2: ", r2)

RMSE:  2.2737367544323206e-13
MSE:  2.2737367544323206e-13
R2:  nan

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

#ML Pipleline for Linear Classification

In [8]:
data ={
    "hours_studied":[2,3,4,5,6,7,8,9],
    "attendance":[50,60,70,80,85,90,95,100],
    "passed":[0,0,0,1,1,1,1,1]
}

df=pd.DataFrame(data)
df.to_csv("students.csv",index=False)

#Step 1. Read (& Preprocess)

In [9]:
df=pd.read_csv("students.csv")
df.head()

   hours_studied  attendance  passed
0              2          50       0
1              3          60       0
2              4          70       0
3              5          80       1
4              6          85       1

#Step 2. Separate Features & Label

In [10]:
X=df[["hours_studied","attendance"]]
y=df["passed"]

#Step 3. Split (divide) the Data

In [11]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

#Step 4. Train Model

In [12]:
from sklearn.linear_model import LogisticRegression

#4.1 Create Model

model= LogisticRegression()

#4.2 Fit Model

model.fit(x_train,y_train)

LogisticRegression()

#Step 5. Predict

In [13]:
y_pred= model.predict(x_test)

#Step 6. Evaluate

In [14]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
accuracy= accuracy_score(y_test,y_pred)
precision= precision_score(y_test,y_pred)
recall= recall_score(y_test,y_pred)
f1= f1_score(y_test,y_pred)
print("Accuracy: ",  accuracy)
print("Precision: ",  precision)
print("Recall: ",  recall)
print("F1: ",  f1)

Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1:  1.0